[
  ./dadada/direnv.nix
  ./dadada/fish.nix
  ./dadada/git.nix
  ./dadada/gpg.nix
  ./dadada/gtk.nix
  ./dadada/keyring.nix
  ./dadada/kitty
  ./dadada/mako.nix
  ./dadada/session.nix
  ./dadada/ssh.nix
  ./dadada/sway
  ./dadada/syncthing.nix
  ./dadada/termite.nix
  ./dadada/tmux.nix
  ./dadada/vim
  ./dadada/xdg.nix
  ./dadada/zsh.nix
]
