[language-server.rust-analyzer]
config = { rust-analyzer = { checkOnSave = { command = "clippy" } } }

[language-server.nil]
command = "nil"

[language-server.ltex-ls]
command = "ltex-ls"

[[language]]
name = "rust"
language-servers = [ {name="rust-analyzer"} ]

[[language]]
name = "latex"
language-servers = [{ name = "ltex-ls" }]
file-types = ["tex"]
scope = "source.latex"
roots = []

[[language]]
name = "nix"
file-types = ["nix"]
language-servers = [{ name = "nil" }]
