# XTerm's default colors
[primary]
# Default colors
background = '0xffffff'
foreground = '0x000000'

[normal]
# Normal colors
black = '0x000000'
red = '0xcd0000'
green = '0x00cd00'
yellow = '0xcdcd00'
blue = '0x0000ee'
magenta = '0xcd00cd'
cyan = '0x00cdcd'
white = '0xe5e5e5'

[bright]
# Bright colors
black = '0x7f7f7f'
red = '0xff0000'
green = '0x00ff00'
yellow = '0xffff00'
blue = '0x5c5cff'
magenta = '0xff00ff'
cyan = '0x00ffff'
white = '0xffffff'
