#!/usr/bin/env bash

set -e
set -o pipefail

if [ -z "$1" ]
then
	echo "usage: deploy <hostname>"
	exit 1
fi

git push

gen-config $1 | ssh "$1".dadada.li 'sudo bash -c "cat - > /etc/nixos/configuration.nix && (nixos-rebuild test && nixos-rebuild switch) || (nixos-rebuild switch --rollback && exit 1)"'
